baseURL = "https://mikhail.io/"
languageCode = "en-us"
title = "Mikhail Shilkov"
copyright = "Mikhail Shilkov - All rights reserved"

assetDir = "assets"
summaryLength = 25
enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "vs"
googleAnalytics = "UA-59218480-1"
disqusShortname = "mikhailio"

[outputs]
  home     = ["HTML", "XML"]
  section  = ["HTML"]

[mediaTypes."application/xml"]
  suffixes = [""]
  delimiter = ""

[outputFormats.XML]
  mediatype = "application/xml"
  baseName = "feed"

[markup.goldmark.renderer]
  unsafe= true

[params]
  favicon = "/favicon.ico"
  description ="Serverless, Cloud, Azure, AWS, F#, Functional Programming, and more"
  feedSections="2019"

[params.author]
  name = "Mikhail Shilkov"
  thumbnail = "/images/author.jpg"

[params.index]
  title = "Mikhail Shilkov"

[params.social]
  linkedin = "MikhailShilkov"
  github = "MikhailShilkov"
  twitter = "MikhailShilkov"
  medium = "MikhailShilkov"
  devto = "mikhailshilkov"

## Main Menu
[[menu.main]]
    name = "TOPICS"
    weight = 100
    identifier = "topics"
    url = "/tags/"
[[menu.main]]
    name = "ARCHIVES"
    weight = 200
    identifier = "archives"
    url = "/archives/"
[[menu.main]]
    name = "TALKS"
    weight = 400
    identifier = "talks"
    url = "/talks/"
[[menu.main]]
    name = "ABOUT"
    weight = 500
    identifier = "about"
    url = "/about/"

## talks
[[params.talks]]
    year = 2020
    date = "Sep 7"
    title = "Cloud Management Superpowers with Pulumi"
    link = "https://www.meetup.com/dutch-cloud-meetup/events/272619261/"
    event = "Dutch Cloud Meetup (virtual)"
    slides = "https://speakerdeck.com/mikhailshilkov/cloud-management-superpowers-with-pulumi"
[[params.talks]]
    year = 2020
    date = "Aug 27"
    title = "Azure Management Superpowers with Pulumi"
    link = "https://www.meetup.com/Stockholm-Azure-Meetup/events/267850663/"
    event = "Stockholm Azure Meetup (virtual)"
    slides = "https://speakerdeck.com/mikhailshilkov/cloud-management-superpowers-with-pulumi"
[[params.talks]]
    year = 2020
    date = "Aug 26"
    title = "Azure Management Superpowers with Pulumi"
    link = "https://www.gaug.co.uk"
    event = "Glasgow Azure User Group (virtual)"
    slides = "https://speakerdeck.com/mikhailshilkov/cloud-management-superpowers-with-pulumi"
[[params.talks]]
    year = 2020
    date = "Aug 17"
    title = "Azure Serverless Infrastructure As Code (Workshop)"
    link = "https://serverless-architecture.io/thehague/program-thehague/"
    event = "Serverless Architecture Conference The Hague 2020"
    labs = "https://github.com/mikhailshilkov/azure-serverless-workshop"
    slides = "https://github.com/mikhailshilkov/azure-serverless-workshop/blob/master/ServerlessArchitecture_Workshop_2020.pdf"
[[params.talks]]
    year = 2020
    date = "Jun 5"
    title = "Cloud Superpowers with Pulumi and F#"
    link = "http://fsharpconf.com/"
    event = "F# Conf 2020 (virtual)"
    slides = "https://speakerdeck.com/mikhailshilkov/cloud-superpowers-with-pulumi-and-f-number"
[[params.talks]]
    year = 2020
    date = "Mar 31"
    title = "Azure Infrastructure as C# and F#"
    link = "https://vacd2.azureday.community/#talk-193954"
    event = "Virtual Azure Community Day"
    slides = "https://speakerdeck.com/mikhailshilkov/azure-infrastructure-as-c-number-and-f-number-d5753ca1-c28f-4a1e-a3fd-134f9ec270a2"
[[params.talks]]
    year = 2020
    date = "Mar 25"
    title = "Infrastructure as Software"
    link = "https://devopspro.lt/mikhail-shilkov/"
    event = "DevOps Pro Europe 2020 (virtual)"
    slides = "https://speakerdeck.com/mikhailshilkov/infrastructure-as-software"
[[params.talks]]
    year = 2020
    date = "Feb 25"
    title = "Azure Infrastructure as C# and F#"
    link = "https://www.microsoft.com/cs-cz/ignite-the-tour/prague"
    event = "Microsoft Ignite The Tour | Prague"
    slides = "https://speakerdeck.com/mikhailshilkov/azure-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Feb 20"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/dutchdotnet/events/267776963"
    event = "Dutch .Net Group"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
    video = "https://www.youtube.com/watch?v=zHjz-yTg0qI"
[[params.talks]]
    year = 2020
    date = "Feb 19"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/Skane-Azure-User-Group/events/268057791/"
    event = "Skåne Azure User Group, Malmö, Sweden"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
    video = "https://www.youtube.com/watch?v=0qkkRRysqe8"
[[params.talks]]
    year = 2020
    date = "Feb 18"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/Copenhagen-Net-User-Group/events/268445025/"
    event = "Copenhagen .NET user group"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Feb 18"
    title = "Workshop: Azure Infrastructure as Code with Pulumi and C#"
    link = "https://www.meetup.com/Azure-Usergroup-Denmark/events/268445103/"
    event = "Azure Usergroup Denmark"
    slides = "https://github.com/pulumi/infrastructure-as-code-workshop/blob/master/labs/azure/csharp/Infrastructure%20as%20Code%20Workshop%20Azure.pdf"
    labs = "https://github.com/pulumi/infrastructure-as-code-workshop/tree/master/labs/azure/csharp"
[[params.talks]]
    year = 2020
    date = "Feb 17"
    title = "Introduction to F# and Functional Programming"
    link = "https://www.meetup.com/dotnet-amsterdam/events/267228367/"
    event = "dotnet Amsterdam meetup"
    slides = "https://mikhail.io/talks/why-fsharp2/"
    video = "https://www.youtube.com/watch?v=F5bm2em5kRU"
[[params.talks]]
    year = 2020
    date = "Feb 12"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/dotnetsouthwest/events/268110936/"
    event = ".NET South West meetup, Bristol, UK"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
    video = "https://www.youtube.com/watch?v=SsvfsAJdLFI"
[[params.talks]]
    year = 2020
    date = "Feb 11"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/dotnetsoutheast/events/268137504/"
    event = ".NET South East meetup, Brighton, UK"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Jan 30"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://www.meetup.com/netcorebcn/events/267108105/"
    event = "Barcelona .NET Core meetup"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
[[params.talks]]
    year = 2020
    date = "Jan 17"
    title = "Cloud Infrastructure as C# and F# with Pulumi"
    link = "https://dotnetfriday.nl"
    event = "DotNetFriday, Utrecht, NL"
    slides = "https://speakerdeck.com/mikhailshilkov/pulumi-cloud-infrastructure-as-c-number-and-f-number"
